---
--- Generated by ByteMagic-Lyu
--- DateTime: 2022/10/3 16:48
---

--local lock = KEYS[1]
--local ip   = ARGV[1]
--local ttl  = ARGV[2] + 0

local ip = redis.call('GET', KEYS[1])
-- no instance running now
if ip == false then
    local result = redis.call('SET', KEYS[1],  ARGV[1], 'NX', 'EX', ARGV[2]) -- lock grab
    if result ~= false and result.ok == 'OK' then
        return 1 -- lock grab success
    end

-- has instance running now
else if ip ~= false and ip == ARGV[1] then
    redis.call('EXPIRE', KEYS[1], ARGV[2]) -- lock grab，renewal
    return 2 -- renewal success
end
end

return 0 -- fail to grab lock
